language: php

dist: xenial

php:
  - 7.4

services:
  - mysql

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install

before_script:
  - sudo mysql -e 'create database homestead;'
  - composer self-update
  - cp .env.testing.example .env
  - php artisan key:generate
  - php artisan jwt:secret --force
  - php artisan migrate

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
