language: php

dist: xenial

php:
  - 7.4

addons:
  mariadb: '10.5'

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install

before_script:
  - sudo mysql -e 'create database homestead;'
  - sudo mysql -e 'CREATE USER glacius@localhost IDENTIFIED BY glacius;'
  - sudo mysql -e 'GRANT ALL PRIVILEGES ON *.* TO glacius@localhost IDENTIFIED BY glacius; FLUSH PRIVILEGES;'
  - composer self-update
  - cp .env.testing.example .env
  - php artisan key:generate
  - php artisan jwt:secret --force
  - php artisan migrate

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
